### ISSUE TITLE
IncompatibleClassChangeError in 1.6.15

### ISSUE THREAD

**Issue by svenwiegand** [scala-android/sbt-android#286]
After updating `sbt-android` to 1.6.15 trying to load the project brings the following error

```
> java.lang.IncompatibleClassChangeError: Found class scalaz.Memo, but interface was expected
        at argonaut.PrettyParams.<init>(PrettyParams.scala:112)
        at argonaut.PrettyParamss$class.$init$(PrettyParams.scala:252)
        at argonaut.Argonaut$.<init>(Argonaut.scala:3)
        at argonaut.Argonaut$.<clinit>(Argonaut.scala)
        at com.hanhuy.sbt.bintray.UpdateChecker$$anonfun$apply$5.apply(UpdateChecker.scala:32)
        at com.hanhuy.sbt.bintray.UpdateChecker$$anonfun$apply$5.apply(UpdateChecker.scala:30)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
java.lang.NoClassDefFoundError: Could not initialize class argonaut.Argonaut$
        at com.hanhuy.sbt.bintray.UpdateChecker$$anonfun$apply$5.apply(UpdateChecker.scala:32)
        at com.hanhuy.sbt.bintray.UpdateChecker$$anonfun$apply$5.apply(UpdateChecker.scala:30)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

Downgrading back to 1.6.14 makes the error disappear.

**Comment by pfn** [comment]
You need to upgrade any plugins that use scalaz. If you're using coursier,
you'll need to update to M14, and if you're using any of my other plugins
you'll need to update to the latest

**Comment by svenwiegand** [comment]
Thanks for the tip. Updatding protify to 1.3.2 and gms to 0.2 did the trick.
